### ISSUE TITLE
WebGL node-webkit example doesn't work out of the box

### ISSUE THREAD

**Issue by wildeyes** [Dica-Developer/generator-node-webkit#71]
```shell
Uncaught node.js Error 

TypeError: Cannot read property 'getExtension' of null
    at initGL (file:///C:/Users/USER~1/AppData/Local/Temp/nw4612_9195/js/three.min.js:21422:33)
    at new THREE.WebGLRenderer (file:///C:/Users/USER~1/AppData/Local/Temp/nw4612_9195/js/three.min.js:14887:2)
    at init (file:///C:/Users/USER~1/AppData/Local/Temp/nw4612_9195/js/showlogo3d.js:61:23)
    at HTMLDocument.<anonymous> (file:///C:/Users/USER~1/AppData/Local/Temp/nw4612_9195/js/showlogo3d.js:29:5)
```
![capture-yo-nw](https://cloud.githubusercontent.com/assets/1652108/7104771/09d3d5bc-e100-11e4-96b5-3db4ec7d83cf.PNG)

Generator doesn't pack required files?

**Comment by mschaaf** [comment]
With what node-webkit version you are trying the webgl example?

**Comment by wildeyes** [comment]
0.8.6

**Comment by mschaaf** [comment]
Then it seem that three.js from the example is not compatible with node-webkit 0.8.6. And we can't do much about this because we don't maintain the examples nor three.js.
Could you please test if 0.10 or newer version of node-webkit works with the example?

**Comment by mschaaf** [comment]
Thanks for your help in improving generator-node-webkit, we close this because it uses an old version of node-webkit which we don't support anymore. Please reopen if the bug still persists in v0.10 or later.
