### ISSUE TITLE
Cannot read property 'statusCode' of undefined

### ISSUE THREAD

**Issue by kessiler** [Dica-Developer/generator-node-webkit#82]
When the connection fails to check if the version of nw it's available, displays the error below:

TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (c:\nodejs\node_modules\generator-node-webkit\generator
s\download\index.js:47:25)
    at self.callback (c:\nodejs\node_modules\generator-node-webkit\node_modules\
request\request.js:198:22)
    at Request.emit (events.js:107:17)
    at Request.onRequestError (c:\nodejs\node_modules\generator-node-webkit\node
_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:107:17)
    at Socket.socketErrorListener (_http_client.js:271:9)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)

**Comment by mschaaf** [comment]
@kessiler Please describe what commands you called and the answer yo gave to the generator-node-webkit questions. Thanks.
